# Generated by Django 2.2.1 on 2019-07-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
