# Generated by Django 2.2.1 on 2019-07-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20190710_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='erp.Farm'),
        ),
    ]
